storage:
  postgres:
    postgres_db:
      username: postgres
      password: postgres
      hostname: postgres_source
      db_name: source_db
      port: 5432

scheduler:
  module: dagster.core.scheduler
  class: DagsterDaemonScheduler

run_coordinator:
  module: dagster.core.run_coordinator
  class: QueuedRunCoordinator

run_launcher:
  module: dagster.core.launcher
  class: DefaultRunLauncher
